### ISSUE TITLE
Build QA test plan

### ISSUE THREAD

**Issue by rayan-saleh** [Arda-Computer/Arda#37]
### Objective
1. Test full range of features and fix major bugs
2. Get to working prototype for all inputs
3. Do within 3 days

### Plan

- [ ] Accept and switch between all input modes (inc eye-tracking, voice, controllers, hand, keyboard and mouse) - eyetracking calibration
- [ ] Customise bridge/bookmarks - hold state and reset option
- [ ] Constant 72+ FPS (no lag), even at high XRRes
- [ ] Attractive UI
- [ ] Build for any (quest) headset

### Todo
1. create each section above as a separate ticket and start fixing - lets do 1 a day
