### ISSUE TITLE
Input testing

### ISSUE THREAD

**Issue by rayan-saleh** [Arda-Computer/Arda#39]
Accept and switch between all input modes (inc eye-tracking, voice, controllers, hand, keyboard and mouse) - eyetracking calibration

### TODO:
- [x] toggle to turn of/on laser
- [x] eye tracking calibration
- [x] reset cursor proprely
- [x] toggle between inputs correctly
